server {
    listen 80;
    listen [::]:80;
    server_name okemily.com www.okemily.com;

    root /var/www/okemily;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
}
